language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
      global:
        - secure: "N1F9JPqNi/V91xNEfAPrdj7fEUNEJeueGVguH1gijNg8oWnMtzPc6kNnadpk8QwCNaHnKPqDcWxFbYohrovT8nGJz+aN9l4orsXQDRK0iZmuD+ydXJbzeWdXJdkH98UanAyO9FYnsPnZhnV2CLZ7VwWF+UY8iPzjXn5jqZIZVNU="
        - GIT_COMMITTER_NAME=kitalab
        - GIT_COMMITTER_EMAIL=nc@withone.co.jp
        - GIT_AUTHOR_NAME=kitalab
        - GIT_AUTHOR_EMAIL=nc@withone.co.jp

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
